option(ENABLE_CCACHE "Enable compiler cache (ccache/sccache) [default: ON]" ON)
if(ENABLE_CCACHE)
    if(NOT DEFINED CMAKE_CXX_COMPILER_LAUNCHER)
        find_program(CCACHE sccache DOC "sccache tool path")
        if(NOT CCACHE)
            find_program(CCACHE ccache DOC "ccache tool path")
        endif()

        if(CCACHE)
            set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE})
            set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE})
            message(STATUS "[ccache] Enabled: ${CCACHE}")
        else()
            message(STATUS "[ccache] Disabled: Not found.")
        endif()
    else()
        message(STATUS "[ccache] Using pre-configured launcher: ${CMAKE_CXX_COMPILER_LAUNCHER}")
    endif()
else()
    message(STATUS "[ccache] Disabled.")
endif()
